### PR TITLE
OS X instructions for installing git

### PR DESCRIPTION
**Pull request by neorix11**

### CODE REVIEW

**Comment by brianhankins** [comment]
LGTM

**Review by brianhankins — APPROVED** [review]

**Review by mtliendo — APPROVED** [review]
stamp=approved

**Review by jpdillingham — APPROVED** [review]

**Comment by jpdillingham** [comment]
Merging because I don't think we can rely on @nickolasacosta to review ;)

**Comment by ghost** [comment]
I thought we decided on two reviewers, not three or four.

**Comment by neorix11** [comment]
This was pre-that decision.

**Pull request merged**
